[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test'
cache_path = 'cache_forge'
script = 'scripts'
# solc_version = "0.8.17"

# optimizer = true
# optimizer_runs = 100
# solc_version = "0.8.20"
optimizer = true
optimizer_runs = 200
