//pair to column names mapping for the rail database
export const BitFinexPairs = {
  bitcoin: "btcusd",
  ethereum: "ethusd",
  solana: "solusd",
  litecoin: "ltcusd",
  monero: "xmrusd",
  polkadot: "dotusd",
  cardano: "adausd",
  eos: "eosusd",
  chainlink: "link:usd",
  dogecoin: "doge:usd",
  bitcoincash: "bchn:usd",
  ethereumclassic: "etcust",
  xaut: "xaut:usd",
  ripple: "xrpusd",
  // Unavailable
  // 'binancecoin:',
  // 'steth:'
  // 'steller:'
  // 'okb:',
  // 'bitcoincashsv:'
}
export const BybitPairs = {
  bitcoin: "BTCUSDT",
  ethereum: "ETHUSDT",
  solana: "SOLUSDT",
  litecoin: "LTCUSDT",
  binancecoin: "BNBUSDT",
  polkadot: "DOTUSDT",
  cardano: "ADAUSDT",
  eos: "EOSUSDT",
  chainlink: "LINKUSDT",
  dogecoin: "DOGEUSDT",
  bitcoincash: "BCHUSDT",
  ethereumclassic: "ETCUSDT",
  ripple: "XRPUSDT",
  steth: "STETHUSDT",
  // ** Unavailable cryptos
  // 'xaut': '',
  // 'monero': '',
  // 'steller:',
  // 'okb:',
  // 'bitcoincashsv:'
}

export const nameToSymbol = {
  bitcoin: "BTC",
  ethereum: "ETH",
  solana: "SOL",
  litecoin: "LTC",
  binancecoin: "BNB",
  polkadot: "DOT",
  cardano: "ADA",
  eos: "EOS",
  chainlink: "LINK",
  dogecoin: "DOGE",
  bitcoincash: "BCH",
  ethereumclassic: "ETC",
  ripple: "XRP",
  steth: "STETH",
  xaut: "GOLD",
  monero: "XMR",
  okb: "OKB",
  bitcoincashsv: "BSV",
}

export const stockDetails:{[key:string]: string[]} = {
  'ANFI': ['anfi', 'Anti Inflation Index'],
  'CRYPTO5': ['crypto5', 'Crypto 5'],
  'MAG7': ['mag7', 'Magnificent 7'],
  // 'ARBIn': ['sci', 'Arbitrum Ecosystem Index'],
  'ARBEI': ['arbie', 'Arbitrum Ecosystem Index'],
  // 'ARBEI_REG': ['arbie', 'Arbitrum Ecosystem Index Regresion'],
  // 'ARBEI_REG_V2': ['arbie', 'Arbitrum Ecosystem Index Regresion V2'],
  'V': ['visa', 'Visa'],
  'SPDR': ['sandp', 'S&P 500'],
  'DJI': ['dow', 'Dow Jones Industrial Average'],
  'NASDAQ': ['nasdaq', 'NASDAQ Composite '],
  'NYSE': ['nyse', 'NYSE COMPOSITE'],
  'ASML': ['asml', 'ASML Holding N.V'],
  'PYPL': ['paypal', 'Paypal'],
  'MSFT': ['microsoft', 'Microsoft'],
  'AAPL': ['apple', 'Apple'],
  'GOOGL': ['alphabet', 'Alphabet Inc.'],
  'AMZN': ['amazon', 'Amazon'],
  '0700': ['tencent', 'Tencent Holdings Limited'],
  'TSM': ['tsmc', 'Taiwan Semiconductor Manufacturing Company Limited'],
  'XOM': ['exxon_mob', 'Exxon Mobil Corporation'],
  'NVDA': ['nvidia', 'Nvidia'],
  'UNH': ['unitedhealth_group', 'UnitedHealth Group Incorporated'],
  'JNJ': ['johnson_n_johnson', 'Johnson & Johnson'],
  'MC': ['lvmh', 'LVMH Moët Hennessy - Louis Vuitton, Société Européenne'],
  'TSLA': ['tesla', 'Tesla'],
  'JPM': ['jpmorgan', 'JPMorgan Chase & Co.'],
  'WMT': ['walmart', 'Walmart'],
  'META': ['meta', 'Meta'],
  'SPY': ['spdr', 'SPDR S&P 500 ETF Trust '],
  'MA': ['mastercard', 'Mastercard Incorporated'],
  'CVX': ['chevron_corp', 'Chevron Corporation'],
  'BRK.A': ['berkshire_hathaway', 'Berkshire Hathaway Inc'],
  'XAU':['gold', 'Gold'],
  'LITHIUM':['lithium', 'Lithium'],
  'CL':['oil', 'Crude Oil'],
  'HG':['copper', 'Copper'],
  'SI':['silver', 'Silver']

}
