export const stockDetails = {
    'ANFI': ['anfi', 'Anti Inflation Index'],
    'CRYPTO5': ['crypto5', 'Crypto 5'],
    // 'STOCK5': ['stock5', 'Stock5'],
    'MAG7': ['mag7', 'Magnificient 7'],
    'ARBIn': ['sci', 'Arbitrum Ecosystem Index'],
    'ARBEI': ['arbie', 'Arbitrum Ecosystem Index'],
    'V': ['visa', 'Visa'],
    'GSPC': ['sandp', 'S&P 500'],
    'DJI': ['dow', 'Dow Jones Industrial Average'],
    'IXIC': ['nasdaq', 'NASDAQ Composite '],
    'NYA': ['nyse', 'NYSE COMPOSITE'],
    'ASML': ['asml', 'ASML Holding N.V'],
    'PYPL': ['paypal', 'Paypal'],
    'MSFT': ['microsoft', 'Microsoft'],
    'AAPL': ['apple', 'Apple'],
    'GOOGL': ['alphabet', 'Alphabet Inc.'],
    'AMZN': ['amazon', 'Amazon'],
    'TCEHY': ['tencent', 'Tencent Holdings Limited'],
    'TSM': ['tsmc', 'Taiwan Semiconductor Manufacturing Company Limited'],
    'XOM': ['exxon_mob', 'Exxon Mobil Corporation'],
    'NVDA': ['nvidia', 'Nvidia'],
    'UNH': ['unitedhealth_group', 'UnitedHealth Group Incorporated'],
    'JNJ': ['johnson_n_johnson', 'Johnson & Johnson'],
    'LVMHF': ['lvmh', 'LVMH Moët Hennessy - Louis Vuitton, Société Européenne'],
    'TSLA': ['tesla', 'Tesla'],
    'JPM': ['jpmorgan', 'JPMorgan Chase & Co.'],
    'WMT': ['walmart', 'Walmart'],
    'META': ['meta', 'Meta'],
    'SPY': ['spdr', 'SPDR S&P 500 ETF Trust '],
    'MA': ['mastercard', 'Mastercard Incorporated'],
    'CVX': ['chevron_corp', 'Chevron Corporation'],
    'BRKA': ['berkshire_hathaway', 'Berkshire Hathaway Inc'],
    'GOLD':['gold', 'Gold'],
    'LITHIUM':['lithium', 'Lithium'],
    'CRUDEOIL':['oil', 'Crude Oil'],
    'COPPER':['copper', 'Copper'],
    'SILVER':['silver', 'Silver'],
    'BTC':['bitcoin', 'Bitcoin'],
    'ARB':['arbitrum', 'Arbitrum'],
    'ETH':['ethereum', 'Ethereum'],

}